/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.EscrowCreationAttachment');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.EscrowDecisionType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.EscrowCreationAttachment = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.EscrowCreationAttachment.repeatedFields_, null);
};
goog.inherits(proto.EscrowCreationAttachment, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.EscrowCreationAttachment.displayName = 'proto.EscrowCreationAttachment';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.EscrowCreationAttachment.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.EscrowCreationAttachment.prototype.toObject = function(opt_includeInstance) {
  return proto.EscrowCreationAttachment.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.EscrowCreationAttachment} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.EscrowCreationAttachment.toObject = function(includeInstance, msg) {
  var f, obj = {
    version: jspb.Message.getFieldWithDefault(msg, 1, 0),
    amount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    requiredsigners: jspb.Message.getFieldWithDefault(msg, 3, 0),
    signersList: jspb.Message.getRepeatedField(msg, 4),
    deadline: jspb.Message.getFieldWithDefault(msg, 5, 0),
    deadlineaction: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.EscrowCreationAttachment}
 */
proto.EscrowCreationAttachment.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.EscrowCreationAttachment;
  return proto.EscrowCreationAttachment.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.EscrowCreationAttachment} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.EscrowCreationAttachment}
 */
proto.EscrowCreationAttachment.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAmount(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRequiredsigners(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setSignersList(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDeadline(value);
      break;
    case 6:
      var value = /** @type {!proto.EscrowDecisionType} */ (reader.readEnum());
      msg.setDeadlineaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.EscrowCreationAttachment.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.EscrowCreationAttachment.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.EscrowCreationAttachment} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.EscrowCreationAttachment.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getRequiredsigners();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSignersList();
  if (f.length > 0) {
    writer.writePackedUint64(
      4,
      f
    );
  }
  f = message.getDeadline();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getDeadlineaction();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional uint32 version = 1;
 * @return {number}
 */
proto.EscrowCreationAttachment.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.EscrowCreationAttachment.prototype.setVersion = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 amount = 2;
 * @return {number}
 */
proto.EscrowCreationAttachment.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.EscrowCreationAttachment.prototype.setAmount = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 requiredSigners = 3;
 * @return {number}
 */
proto.EscrowCreationAttachment.prototype.getRequiredsigners = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.EscrowCreationAttachment.prototype.setRequiredsigners = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated uint64 signers = 4;
 * @return {!Array<number>}
 */
proto.EscrowCreationAttachment.prototype.getSignersList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<number>} value */
proto.EscrowCreationAttachment.prototype.setSignersList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.EscrowCreationAttachment.prototype.addSigners = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


proto.EscrowCreationAttachment.prototype.clearSignersList = function() {
  this.setSignersList([]);
};


/**
 * optional uint32 deadline = 5;
 * @return {number}
 */
proto.EscrowCreationAttachment.prototype.getDeadline = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.EscrowCreationAttachment.prototype.setDeadline = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional EscrowDecisionType deadlineAction = 6;
 * @return {!proto.EscrowDecisionType}
 */
proto.EscrowCreationAttachment.prototype.getDeadlineaction = function() {
  return /** @type {!proto.EscrowDecisionType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.EscrowDecisionType} value */
proto.EscrowCreationAttachment.prototype.setDeadlineaction = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};


